language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
# command to run tests
script: python -m unittest discover
after_success:
  - coverage run -m unittest discover
  - codecov
